name: flutter_dialogflow_web
description: Flutter package for makes it easy to integrate dialogflow
version: 0.0.1
author: Victor Alfonso Rodas Oña <victordevcode@gmail.com>
homepage: https://github.com/VictorRancesCode/flutter_dialogflow_web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  http: ^0.12.0+2

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0
